name: dart_ssss
description: A Dart library that implements Shamir's Secret Sharing Scheme over GF(256).
version: 0.0.2
homepage: https://www.github.com/gching/dart_ssss
author: Gavin Ching <gavinchingy@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  test: ^0.12.0
